Repository tpe-doit/Taipei-City-Dashboard, pull requests merged in 2023-12, with the labels that each got.

#82 Added Tag Tooltip
  src/components/components/ComponentContainer.vue
  src/components/components/ComponentMapChart.vue
  src/components/utilities/ComponentTag.vue
  src/components/utilities/TagTooltip.vue
Labels: enhancement

#85 Adjustments and Fixes to 112A Contribution
  public/chartData/164.json
  public/chartData/165.json
  public/chartData/166.json
  public/dashboards/all_components.json
  public/dashboards/all_contributors.json
  public/dashboards/all_dashboards.json
  public/images/contributors/我們都是112A.png
  public/images/contributors/林育緹.png
  public/images/contributors/王佑豪.png
  public/images/contributors/蔡立倫.png
  public/images/contributors/謝芝嫻.png
  public/images/contributors/賴彥良.png
  src/components/charts/DistrictChart.vue
Labels: component

#91 [TWM] Add component and feature
  public/chartData/150.json
  public/chartData/151.json
  public/dashboards/all_components.json
  public/historyData/151.json
  public/mapData/childcare_resource.geojson
  src/assets/configs/apexcharts/chartTypes.js
  src/components/charts/BarChartWithGoal.vue
  src/components/charts/IconPercentChart.vue
  src/components/charts/MixedColumnLineChart.vue
  src/components/components/ComponentMapChart.vue
  src/components/utilities/MobileLayerTab.vue
  src/main.js
  src/store/mapStore.js
Labels: enhancement, component

#100 [捕蚊燈] (Component) 156 maternity_hospitals & (Feature) SpeedometerChart
  public/chartData/156.json
  public/dashboards/all_components.json
  public/dashboards/all_dashboards.json
  public/historyData/156.json
  public/mapData/maternity_hospitals.geojson
  src/assets/configs/apexcharts/chartTypes.js
  src/components/charts/SpeedometerChart.vue
Labels: enhancement, component

#103 Refactor mosquito's PR
  public/chartData/156.json
  public/dashboards/all_components.json
  public/dashboards/all_contributors.json
  public/dashboards/all_dashboards.json
  public/historyData/156.json
  public/images/contributors/劉庭均.png
  public/images/contributors/吳典睿.png
  public/images/contributors/吳承羲.png
  public/images/contributors/李冠儀.png
  public/images/contributors/許富盈.png
  public/images/contributors/陳柏睿.png
  public/mapData/maternity_hospitals_1.geojson
  public/mapData/maternity_hospitals_2.geojson
  public/mapData/maternity_hospitals_3.geojson
  src/components/charts/PolarAreaChart.vue
  src/components/charts/SpeedometerChart.vue
Labels: enhancement, component

#97 create residential_safety component
  public/chartData/152.json
  public/dashboards/all_components.json
  public/dashboards/all_dashboards.json
Labels: component

#105 Change dashboard colors
  public/dashboards/all_components.json
Labels: enhancement
