Repository tpe-doit/Taipei-City-Dashboard, pull requests merged in 2024-03, with the labels that each got.

#131 User related apis minor debugging
  Taipei-City-Dashboard-BE/global/consts.go
  Taipei-City-Dashboard-BE/internal/app/controllers/dashboard.go
  Taipei-City-Dashboard-BE/internal/app/controllers/user.go
  Taipei-City-Dashboard-BE/internal/app/middleware/common.go
  Taipei-City-Dashboard-BE/internal/app/routes/router.go
  Taipei-City-Dashboard-FE/index.html
  Taipei-City-Dashboard-FE/src/components/dialogs/LogIn.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/UserSettings.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminEditIssue.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminEditUser.vue
  Taipei-City-Dashboard-FE/src/components/utilities/bars/AdminSideBar.vue
  Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue
  Taipei-City-Dashboard-FE/src/router/axios.js
  Taipei-City-Dashboard-FE/src/router/index.js
  Taipei-City-Dashboard-FE/src/store/adminStore.js
  Taipei-City-Dashboard-FE/src/store/authStore.js
  Taipei-City-Dashboard-FE/src/store/dialogStore.js
  Taipei-City-Dashboard-FE/src/views/admin/AdminIssue.vue
  Taipei-City-Dashboard-FE/src/views/admin/AdminOverview.vue
  Taipei-City-Dashboard-FE/src/views/admin/AdminUser.vue
Labels: enhancement

#133 Refactor backend code
  Taipei-City-Dashboard-BE/app/app.go
  Taipei-City-Dashboard-BE/app/cache/redis.go
  Taipei-City-Dashboard-BE/app/controllers/auth.go
  Taipei-City-Dashboard-BE/app/controllers/componentConfig.go
  Taipei-City-Dashboard-BE/app/controllers/componentData.go
  Taipei-City-Dashboard-BE/app/controllers/dashboard.go
  Taipei-City-Dashboard-BE/app/controllers/isso.go
  Taipei-City-Dashboard-BE/app/controllers/issue.go
  Taipei-City-Dashboard-BE/app/controllers/user.go
  Taipei-City-Dashboard-BE/app/initial/initial.go
  Taipei-City-Dashboard-BE/app/middleware/auth.go
  Taipei-City-Dashboard-BE/app/middleware/common.go
  Taipei-City-Dashboard-BE/app/middleware/rateLimit.go
  Taipei-City-Dashboard-BE/app/models/auth.go
  Taipei-City-Dashboard-BE/app/models/componentConfig.go
  Taipei-City-Dashboard-BE/app/models/componentData.go
  Taipei-City-Dashboard-BE/app/models/dashboard.go
  Taipei-City-Dashboard-BE/app/models/database.go
  Taipei-City-Dashboard-BE/app/models/issue.go
  Taipei-City-Dashboard-BE/app/models/user.go
  Taipei-City-Dashboard-BE/app/routes/router.go
  Taipei-City-Dashboard-BE/app/util/auth.go
  Taipei-City-Dashboard-BE/app/util/common.go
  Taipei-City-Dashboard-BE/app/util/user.go
  Taipei-City-Dashboard-BE/cmd/root.go
  Taipei-City-Dashboard-BE/cmd/sync.go
  Taipei-City-Dashboard-BE/internal/app/controllers/componentConfig.go
  Taipei-City-Dashboard-BE/internal/app/controllers/componentData.go
  Taipei-City-Dashboard-BE/internal/app/controllers/dashboard.go
  Taipei-City-Dashboard-BE/internal/app/controllers/util.go
  Taipei-City-Dashboard-BE/internal/auth/auth.go
  Taipei-City-Dashboard-BE/internal/auth/dashboard.go
  Taipei-City-Dashboard-BE/internal/auth/jwt.go
  Taipei-City-Dashboard-BE/internal/auth/util.go
  Taipei-City-Dashboard-BE/internal/db/postgres/models/auth.go
  Taipei-City-Dashboard-BE/internal/db/postgres/models/componentConfig.go
  Taipei-City-Dashboard-BE/internal/db/postgres/models/componentData.go
  Taipei-City-Dashboard-BE/internal/db/postgres/models/dashboard.go
  Taipei-City-Dashboard-BE/internal/db/postgres/models/issue.go
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue
  Taipei-City-Dashboard-FE/src/views/admin/AdminEditComponent.vue
Labels: bug, enhancement

#137 Fixed Component Info, Timezone, Maintain Bug
  Taipei-City-Dashboard-FE/src/assets/configs/AllTimes.js
  Taipei-City-Dashboard-FE/src/components/charts/ColumnLineChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/GuageChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/HistoryChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/TimelineSeparateChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/TimelineStackedChart.vue
  Taipei-City-Dashboard-FE/src/components/components/ComponentContainer.vue
  Taipei-City-Dashboard-FE/src/components/components/ComponentMapChart.vue
  Taipei-City-Dashboard-FE/src/components/components/ComponentPreview.vue
  Taipei-City-Dashboard-FE/src/store/authStore.js
Labels: bug

#140 update isso.go
  Taipei-City-Dashboard-BE/app/controllers/isso.go
Labels: bug

#141 Added Reload Timer and fixed minor bugs
  Taipei-City-Dashboard-FE/src/App.vue
  Taipei-City-Dashboard-FE/src/components/charts/ColumnLineChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/TimelineSeparateChart.vue
  Taipei-City-Dashboard-FE/src/components/charts/TimelineStackedChart.vue
  Taipei-City-Dashboard-FE/src/views/DashboardView.vue
  Taipei-City-Dashboard-FE/src/views/MapView.vue
Labels: bug, enhancement

#142 Fixed Numerous FE Bugs [deploy debug 1]
  Taipei-City-Dashboard-FE/package-lock.json
  Taipei-City-Dashboard-FE/package.json
  Taipei-City-Dashboard-FE/src/components/dialogs/AddComponent.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/ReportIssue.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminAddComponent.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/admin/AdminComponentSettings.vue
  Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue
  Taipei-City-Dashboard-FE/src/main.js
  Taipei-City-Dashboard-FE/src/store/contentStore.js
  Taipei-City-Dashboard-FE/src/views/admin/AdminEditComponent.vue
  Taipei-City-Dashboard-FE/src/views/admin/AdminIssue.vue
  Taipei-City-Dashboard-FE/src/views/admin/AdminUser.vue
Labels: bug

#145 Fixed Bugs and Added 2 Metro Lines [deploy debug 3]
  Taipei-City-Dashboard-FE/src/assets/configs/apexcharts/taipeiMetroLines.js
  Taipei-City-Dashboard-FE/src/assets/styles/globalStyles.css
  Taipei-City-Dashboard-FE/src/components/charts/MetroChart.vue
  Taipei-City-Dashboard-FE/src/components/dialogs/MoreInfo.vue
  Taipei-City-Dashboard-FE/src/components/map/MapContainer.vue
  Taipei-City-Dashboard-FE/src/components/utilities/bars/NavBar.vue
  Taipei-City-Dashboard-FE/src/components/utilities/miscellaneous/MetroCarDensity.vue
Labels: bug, enhancement

#148 Add Isso Logout
  Taipei-City-Dashboard-BE/app/controllers/isso.go
  Taipei-City-Dashboard-BE/app/routes/router.go
  Taipei-City-Dashboard-BE/global/consts.go
  Taipei-City-Dashboard-FE/src/assets/configs/apexcharts/taipeiMetroLines.js
  Taipei-City-Dashboard-FE/src/store/authStore.js
  docker/.env.template
Labels: enhancement

#156 Add default district and village boundaries
  Taipei-City-Dashboard-FE/src/assets/configs/mapbox/mapConfig.js
  Taipei-City-Dashboard-FE/src/components/map/MapContainer.vue
  Taipei-City-Dashboard-FE/src/store/mapStore.js
Labels: enhancement

#157 Added Web App Support
  Taipei-City-Dashboard-FE/index.html
  Taipei-City-Dashboard-FE/public/bitmap.png
  Taipei-City-Dashboard-FE/public/favicon.ico
  Taipei-City-Dashboard-FE/public/logo.ico
  Taipei-City-Dashboard-FE/public/logo.png
  Taipei-City-Dashboard-FE/public/logo.svg
  Taipei-City-Dashboard-FE/public/manifest.json
Labels: enhancement
